# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='RestaurantLocations',
        ),
    ]
