# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20190123_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantLocations',
            new_name='RestaurantLocation',
        ),
    ]
